#################################
#  TCore Settings Configuration #
#################################

# WARNING: Check all the valid langs in the lang directory
lang: en_US

# If true, teleport a player to  data.yml(spawn-location) on join
spawn-teleport: true

# If true, players will not take any type of damage
invincibility: false

# If false, players will not lose food level
food-level-change: true

# If true, players will not be able to break block
no-break-block: false

##########################
#  TCore Chat section    #
##########################

# Valid Placeholders:
# <PLAYER_NAME> = Player name
# <DISPLAY_NAME> = Player Display name
# <FACTION> = Player Faction ** (TFaction depend)
# <LEVEL_COLOR> = Player Level Color ** (Leveling depend)
# <LEVEL> = Player Level ** (Leveling depend)
# <GROUP> = Player Group ** (LuckPerm depend)
# <MESSAGE> = Player Message
chat-format: '<e><LEVEL> <b><PLAYER_NAME><7>: <LEVEL_COLOR><MESSAGE>'
